import type { ComponentType, SVGProps } from "react";
import {
  ArrowRightIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  SparklesIcon,
  FireIcon,
  ClockIcon,
  UserGroupIcon,
  ArrowTrendingUpIcon,
  DocumentTextIcon,
  ShareIcon,
  MagnifyingGlassIcon,
  XMarkIcon,
  CheckIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  EllipsisHorizontalIcon,
  Bars3Icon,
  CircleSmallIcon,
  PlusIcon,
  FolderOpenIcon,
  TrashIcon,
  ArrowTopRightOnSquareIcon,
  LinkIcon,
  TagIcon,
  PlayIcon,
  PauseIcon,
  PhotoIcon,
  HashtagIcon,
  AtSymbolIcon,
  UserIcon,
  FolderIcon,
  BuildingOffice2Icon,
  ChartBarIcon,
  PencilSquareIcon,
  BoltIcon,
  Squares2X2Icon,
  GaugeIcon,
  BadgeCheckIcon,
  CrownIcon,
  RocketLaunchIcon,
  EnvelopeIcon,
  CalendarDaysIcon,
  LockClosedIcon,
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  ChatBubbleLeftEllipsisIcon,
  ListBulletIcon,
  CodeBracketIcon,
  BoldIcon,
  ItalicIcon,
  StrikethroughIcon,
  MusicalNoteIcon,
  RectangleStackIcon,
} from "@heroicons/react/24/outline";

export type LucideIcon = ComponentType<SVGProps<SVGSVGElement>>;

export {
  ArrowRightIcon as ArrowRight,
  ArrowLeftIcon as ArrowLeft,
  ArrowPathIcon as Loader2,
  SparklesIcon as Sparkles,
  FireIcon as Flame,
  ClockIcon as Clock,
  UserGroupIcon as Users,
  ArrowTrendingUpIcon as TrendingUp,
  DocumentTextIcon as StickyNote,
  DocumentTextIcon as FileText,
  ShareIcon as Network,
  MagnifyingGlassIcon as Search,
  XMarkIcon as X,
  CheckIcon as Check,
  ChevronRightIcon as ChevronRight,
  ChevronLeftIcon as ChevronLeft,
  ChevronDownIcon as ChevronDown,
  ChevronUpIcon as ChevronUp,
  EllipsisHorizontalIcon as MoreHorizontal,
  Bars3Icon as Menu,
  CircleSmallIcon as Circle,
  CircleSmallIcon as Dot,
  CircleSmallIcon as CircleDot,
  PlusIcon as Plus,
  FolderOpenIcon as FolderOpen,
  TrashIcon as Trash2,
  ArrowTopRightOnSquareIcon as ArrowUpRight,
  LinkIcon as Link,
  LinkIcon as Link2,
  TagIcon as Tag,
  PlayIcon as Play,
  PauseIcon as Pause,
  PhotoIcon as ImageOff,
  HashtagIcon as Hash,
  AtSymbolIcon as AtSign,
  UserIcon as User,
  FolderIcon as Folder,
  BuildingOffice2Icon as Building2,
  ChartBarIcon as BarChart3,
  PencilSquareIcon as Edit,
  PencilSquareIcon as PenLine,
  BoltIcon as Zap,
  Squares2X2Icon as Layers,
  GaugeIcon as Gauge,
  BadgeCheckIcon as BadgeCheck,
  CrownIcon as Crown,
  RocketLaunchIcon as Rocket,
  EnvelopeIcon as Mail,
  CalendarDaysIcon as Calendar,
  LockClosedIcon as Lock,
  ArrowDownTrayIcon as Download,
  ArrowUpTrayIcon as Upload,
  ChatBubbleLeftEllipsisIcon as Quote,
  ListBulletIcon as List,
  ListBulletIcon as ListOrdered,
  CodeBracketIcon as Code,
  BoldIcon as Bold,
  ItalicIcon as Italic,
  StrikethroughIcon as Strikethrough,
  HashtagIcon as Heading1,
  HashtagIcon as Heading2,
  RectangleStackIcon as PanelLeft,
  Bars3Icon as GripVertical,
  SparklesIcon as Gem,
  ArrowPathIcon as RefreshCw,
  ArrowTopRightOnSquareIcon as ExternalLink,
};
